// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIPRA_FESC.Entities;

#nullable disable

namespace SIPRA_FESC.Migrations
{
    [DbContext(typeof(SipraContext))]
    [Migration("20230904134607_segundaVersionn")]
    partial class segundaVersionn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SIPRA_FESC.Entities.Carrera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Carrera1")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("carrera");

                    b.Property<string>("IdCarrera")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("id_carrera")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdCarrera" }, "id_carrera")
                        .IsUnique();

                    b.ToTable("carrera", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Carrera1 = "Ingenieria de Software",
                            IdCarrera = "c0d7472e-81a5-437f-9a08-91a8f419dc1c"
                        },
                        new
                        {
                            Id = 2,
                            Carrera1 = "Diseño y Administración de Modas",
                            IdCarrera = "f0a46a3b-f1fe-4c66-b7d9-aaba878e3b56"
                        },
                        new
                        {
                            Id = 3,
                            Carrera1 = "Diseño Grafico",
                            IdCarrera = "d8fa7f36-0959-419c-ba44-0a548b803973"
                        },
                        new
                        {
                            Id = 4,
                            Carrera1 = "Gestión Logistica Empresarial",
                            IdCarrera = "3b72e843-946b-4fd1-afa2-a42951895931"
                        },
                        new
                        {
                            Id = 5,
                            Carrera1 = "Administración Turística y Hotelera",
                            IdCarrera = "16a280d1-f2ba-4130-b8c1-3c0f92b7e42c"
                        },
                        new
                        {
                            Id = 6,
                            Carrera1 = "Administración Negocios Internacionales",
                            IdCarrera = "2f73c3ab-9834-4a26-bc21-9e5b805bd48a"
                        },
                        new
                        {
                            Id = 7,
                            Carrera1 = "Administración financiera",
                            IdCarrera = "0329c423-54d7-49e3-8e18-b29b829641a6"
                        });
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("celular");

                    b.Property<string>("CelularJefeInmediato")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("celular_jefe_inmediato");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("correo");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("direccion");

                    b.Property<string>("IdEmpresa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_estudiante");

                    b.Property<int>("IdTipoConvenio")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_tipo_convenio");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("nit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreJefeInmedianto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("nombre_jefe_inmedianto");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEstudiante" }, "id_estudiante");

                    b.HasIndex(new[] { "IdTipoConvenio" }, "id_tipo_convenio");

                    b.ToTable("empresa", (string)null);
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.Evaluacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Evaluacion1")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("evaluacion");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_estudiante");

                    b.Property<string>("IdEvaluacion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("id_evaluacion");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdEstudiante" }, "id_estudiante")
                        .HasDatabaseName("id_estudiante1");

                    b.ToTable("evaluacion", (string)null);
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.Formulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Formulario1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("formulario");

                    b.Property<string>("IdFormulario")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("id_formulario")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdFormulario" }, "id_formulario")
                        .IsUnique();

                    b.ToTable("formularios", (string)null);
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.FormulariosCargado", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_usuario");

                    b.Property<int>("Id")
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("IdFormularioCargado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("id_formulario_cargado")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<int>("Url")
                        .HasColumnType("int(11)")
                        .HasColumnName("url");

                    b.HasKey("IdUsuario", "Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdFormularioCargado" }, "id_formulario_cargado")
                        .IsUnique();

                    b.ToTable("formularios_cargados", (string)null);
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("id_rol")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Rol1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("rol");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdRol" }, "id_rol")
                        .IsUnique();

                    b.ToTable("rol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdRol = "6ba1432b-fcab-4344-9cff-4ab46f2c1069",
                            Rol1 = "Extension"
                        },
                        new
                        {
                            Id = 2,
                            IdRol = "2afa4408-505f-4aa0-9dc9-8764fe41edbd",
                            Rol1 = "Docente"
                        },
                        new
                        {
                            Id = 3,
                            IdRol = "50843a37-c57c-4836-9db3-1f371e35c380",
                            Rol1 = "Estudiante"
                        });
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.TipoConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Convenio")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("convenio");

                    b.Property<string>("IdTipoConvenio")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("id_tipo_convenio")
                        .HasDefaultValueSql("'NULL'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdTipoConvenio" }, "id_tipo_convenio")
                        .IsUnique()
                        .HasDatabaseName("id_tipo_convenio1");

                    b.ToTable("tipo_convenio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Convenio = "CONVENIO",
                            IdTipoConvenio = "367a87ca-25fb-4703-89c9-7bcebbc4c25f"
                        },
                        new
                        {
                            Id = 2,
                            Convenio = "TRABAJA CON EMPRESA",
                            IdTipoConvenio = "9bfba821-0206-4128-95fd-e4dc43c3960e"
                        },
                        new
                        {
                            Id = 3,
                            Convenio = "EMPRESA PROPIA",
                            IdTipoConvenio = "85990258-7c96-43b1-9a8e-6ad8a1d9a0f4"
                        },
                        new
                        {
                            Id = 4,
                            Convenio = "INVESTIGACIÓN",
                            IdTipoConvenio = "2bde822b-50c4-4137-b38f-0e367f3f37be"
                        },
                        new
                        {
                            Id = 5,
                            Convenio = "APRENDIZ UNIVERSITARIO",
                            IdTipoConvenio = "85b3efea-ae16-42c6-a762-bf5d961c7910"
                        });
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.TipoIdentificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("IdTipoIdentificacion")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("id_tipo_identificacion")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("TipoIdentificacion1")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("tipo_identificacion");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "IdTipoIdentificacion" }, "id_tipo_identificacion")
                        .IsUnique();

                    b.ToTable("tipo_identificacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdTipoIdentificacion = "05da7ea4-9523-425f-b8fd-b32475144fd9",
                            TipoIdentificacion1 = "C.C"
                        },
                        new
                        {
                            Id = 2,
                            IdTipoIdentificacion = "e25a28e3-99f7-4498-8e53-546b95d92489",
                            TipoIdentificacion1 = "T.I"
                        });
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("email");

                    b.Property<int?>("IdCarrera")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_carrera");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_rol");

                    b.Property<int?>("IdTipoDocumento")
                        .HasColumnType("int(11)")
                        .HasColumnName("id_tipo_documento");

                    b.Property<string>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("id_usuario")
                        .HasDefaultValueSql("'NULL'");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("nombres");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("varchar(90)")
                        .HasColumnName("numero_identificacion");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.HasIndex(new[] { "IdCarrera" }, "id_carrera")
                        .HasDatabaseName("id_carrera1");

                    b.HasIndex(new[] { "IdRol" }, "id_rol")
                        .HasDatabaseName("id_rol1");

                    b.HasIndex(new[] { "IdTipoDocumento" }, "id_tipo_documento");

                    b.HasIndex(new[] { "IdUsuario" }, "id_usuario")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.Empresa", b =>
                {
                    b.HasOne("SIPRA_FESC.Entities.Usuario", "IdEstudianteNavigation")
                        .WithMany("Empresas")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("empresa_ibfk_1");

                    b.HasOne("SIPRA_FESC.Entities.TipoConvenio", "IdTipoConvenioNavigation")
                        .WithMany("Empresas")
                        .HasForeignKey("IdTipoConvenio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("empresa_ibfk_2");

                    b.Navigation("IdEstudianteNavigation");

                    b.Navigation("IdTipoConvenioNavigation");
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.Evaluacion", b =>
                {
                    b.HasOne("SIPRA_FESC.Entities.Usuario", "IdEstudianteNavigation")
                        .WithMany("Evaluacions")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("evaluacion_ibfk_1");

                    b.Navigation("IdEstudianteNavigation");
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.FormulariosCargado", b =>
                {
                    b.HasOne("SIPRA_FESC.Entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("FormulariosCargados")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("formularios_cargados_ibfk_1");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.Usuario", b =>
                {
                    b.HasOne("SIPRA_FESC.Entities.Carrera", "IdCarreraNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdCarrera")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("usuario_ibfk_2");

                    b.HasOne("SIPRA_FESC.Entities.Rol", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("usuario_ibfk_1");

                    b.HasOne("SIPRA_FESC.Entities.TipoIdentificacion", "IdTipoDocumentoNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdTipoDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("usuario_ibfk_3");

                    b.Navigation("IdCarreraNavigation");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdTipoDocumentoNavigation");
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.Carrera", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.TipoConvenio", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.TipoIdentificacion", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SIPRA_FESC.Entities.Usuario", b =>
                {
                    b.Navigation("Empresas");

                    b.Navigation("Evaluacions");

                    b.Navigation("FormulariosCargados");
                });
#pragma warning restore 612, 618
        }
    }
}
